name: Deploy Laravel to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /var/www/html/trackgo

            sudo git config --global --add safe.directory /var/www/html/trackgo

            sudo git pull origin master

            sudo chown -R apache:apache /var/www/html/trackgo

            cd /var/www/html/trackgo

            sudo -u apache composer install --no-dev --optimize-autoloader

            sudo -u apache php artisan key:generate --force || true
            sudo -u apache php artisan migrate --force || true
            sudo -u apache php artisan config:clear
            sudo -u apache php artisan cache:clear
            sudo -u apache php artisan route:clear
            sudo -u apache php artisan view:clear

            sudo systemctl restart httpd
            sudo systemctl restart php-fpm
          EOF
